function love.conf(t)
    t.identity     = 'longshot' -- The name of the save directory (string)
    t.version      = '11.2'     -- The LÖVE version this game was made for (string)
    t.console      = true       -- Attach a console (boolean, Windows only)
    t.window.title = 'Longshot' -- The window title (string)
    --~ t.window.x = 700                    -- The x-coordinate of the window's position in the specified display (number)
    --~ t.window.y = nil                    -- The y-coordinate of the window's position in the specified display (number)
    --~ t.window.width = 1920                -- The window width (number)
    --~ t.window.height = 1280               -- The window height (number)
end
